### ISSUE TITLE
Provide credentials

### ISSUE THREAD

**Issue by amenophis** [klausmeyer/docker-registry-browser#1]
Hi,
How can i provide credentials to authenticate on the registry ?

Thanks !

**Comment by klausmeyer** [comment]
Hi,

thanks for your interest for my current side-project 🙇.
At the moment I haven't implemented support for any kind of authentication since the registries I'm using the application for are private ones w/o access-restriction.

What kind of authentication would you need?
Are you using the integrated basic-auth or do you have some more complex setup in place?

Cheers, Klaus

**Comment by amenophis** [comment]
Hi,

Only basic authentication.
Should be pretty easy to integrate on the HTTP client !

**Comment by klausmeyer** [comment]
Yes indeed. I've just added the feature. Please have a look at the README where the two environment variables are described you'd need to set.

**Comment by amenophis** [comment]
Thanks it works !
