### ISSUE TITLE
Docker Pull Command

### ISSUE THREAD

**Issue by eana** [klausmeyer/docker-registry-browser#14]
Hello @klausmeyer,

First of all thank you for the effort you're putting into this.

It would be great if you could add a small `Docker Pull Command` box with the `docker pull` command to pull the current `image`.

For example, if you go to https://quay.io/repository/prometheus/prometheus on the right side of the page is a `Pull this container with the following Docker command:` box with the `docker pull` command to pull the latest prometheus version.

Thanks

**Comment by klausmeyer** [comment]
Hey @eana,

I have good news for you - this feature is already implemented 😁 and just not active by default since it requires an additional config option.

Just make sure to have the latest version of the image and define the `PUBLIC_REGISTRY_URL` environment variable with the URL used to pull images from your registry.

For example:

```
PUBLIC_REGISTRY_URL=registry.example.com:5000
```

Best, Klaus

**Comment by eana** [comment]
Thank you

**Comment by klausmeyer** [comment]
You’re welcome 😉
