### ISSUE TITLE
Support HTTPS for docker image

### ISSUE THREAD

**Issue by waldner** [klausmeyer/docker-registry-browser#185]
Seems to me that the official image (https://hub.docker.com/r/klausmeyer/docker-registry-browser/) only supports HTTP access.
So for example additional env variables to specify TLS cert/key locations etc could be used.

**Comment by klausmeyer** [comment]
Hi @waldner,

it's best practice to not directly expose application-servers like the one I'm using in this project (puma) to clients. That's why the application itself does not support to configure TLS.

I would recommend using for example [nginx](http://nginx.org) as a reverse-proxy in front which does the TLS offloading and passes the requests to the application. You can simply run it as another docker container on the same host and link it to the docker-registry-browser container.

**Comment by waldner** [comment]
While in general I agree with you, I was asking about the docker image. It's not uncommon for many self-contained dockerized applications to offer an HTTPS option (to avoid having to spin extra containers just for that). I think it's not difficult to implement and allow the user to enable it via some variables. If not, then of course I'll go with the reverse proxy setup (which is what I do already, after all).

**Comment by klausmeyer** [comment]
Got your point. It shouldn't be difficult to add HTTPS support as the used app server has built-in support for it. It's just about providing a way to enable it and configure the cert/key pair.

I'll see if I can find some time in the next days to give it a try.

**Comment by klausmeyer** [comment]
@waldner I managed to implement something now.

Please check the latest image and have a look at the updated README.

**Comment by waldner** [comment]
Thanks! It works fine.
