### ISSUE TITLE
Sorting tags for images

### ISSUE THREAD

**Issue by RyanLiu6** [klausmeyer/docker-registry-browser#310]
Currently, it seems like the tags are some sort of reversed order based on the tag name itself. Is there any way to sort based on created date or other criteria? It would be really helpful to be able to view the newest and oldest tags.

Thanks! Really liking this solution more than others 😄

**Comment by klausmeyer** [comment]
Hi @RyanLiu6,

thanks for your kind words!

I'll see when I can look into that topic. As you already correctly mentioned the tags currently are sorted by their name in descending order (so if tags are based on versions/timestamps the newest ones are on the top). 

It could be that it's not so easy to order by anything else than the name since the registry API might not provide more information in the tags list endpoint.

**Comment by RyanLiu6** [comment]
Yeah, I've looked into the registry API as well, and it looks like the only way to get such information is to hit `registry/v2/<name>/manifests/<tag>` and then looking at history -> v1Compatibility -> created, a little messy but doable. 

I saw in #267 that you mentioned Portus and their usage of a separate database for this information, which may not be appropriate for all use cases (and may be a lot of work haha).

Do you think it's possible to add that as an option? I'm willing to help as well 😅

**Comment by klausmeyer** [comment]
Exactly - it would be necessary to first fetch the list of all tags and then while iterating over them fire another API request to get the needed details. That's something I'd do really unwillingly.

The database & sync approach is also something I'm currently not doing by design. IMO one of the main advantages of my docker registry UI is the simplicity of setup and run. Adding additional components as requirement would not allow to simply install this application on top of an existing registry since you'd have to initially index the registry into the local database and always keep it up-to-date via some hooks/triggers.

I was thinking about doing some experimentation with just adding that additional API calls to see how much stuff is slowing down and if there are some ways to add caching to improve it - but I haven't had the chance yet to invest some time :)

**Comment by maxboone** [comment]
We're hitting the same runtime problem with our set-up, it doesn't occur when we manually spin up a kubernetes pod but when we do this through a helm-chart (with the container running as nonRoot / user app) it complains about this.

**Comment by vi7** [comment]
Hey @klausmeyer , I've managed to test config via ENV vars and it works. So to sum up sorting feature works as described from my end ✅. Had to update Docker to the latest on my prod server (as well CentOS 7 with kernel v3) in order to get rid of `Could not find a JavaScript runtime`


P.S.:

Some sad news for me as well. It appeared that Docker Registry operates the weird way, meaning that since last Friday out of the blue it started to add freshest tags to the top of the API reply instead of the end as it was always before:

![Screenshot 2021-11-02 at 12 41 20](https://user-images.githubusercontent.com/3525968/139840280-8cfc1869-301f-4e2c-b515-773d52a6294a.png)

This triggers new sorting feature of the Registry Browser as well as my automated Registry cleaner tool (which also relied on API sort) useless for majority of the images. Looks like I'll have to implement chain of API requests to the Registry to get image timestamps and sort tags using them :(

**Comment by klausmeyer** [comment]
Thanks for your feedback.

Unfortunately the API spec for [`GET /v2/<name>/tags/list`](https://docs.docker.com/registry/spec/api/#listing-image-tags) has absolutely no info about the order in which the tags are returned - so I assume it's up to the implementation and cannot be guaranteed in all cases.

I already was expecting that - that's why I named the option "API" in the UI and options.
Do you think the feature is worth shipping like that?

**Comment by vi7** [comment]
I took a brief look to the Registry sources and it looks like it should sort alphabetically (similar to the 'name' sort of yours) but in reality it works differently. Assuming all of these findings IMO there is no real market for the "API-way" of sorting for now

**Comment by vi7** [comment]
Funny thing but today tag sorting in the API reply from the Registry is correct again, meaning tags are sorted from the oldest to newest. Obviously it's dangerous to rely on the API sorting from the automation scripts but maybe it is still makes sense to have 'api sort' feature in the browser. @klausmeyer wdyt?

**Comment by klausmeyer** [comment]
I'll merge my change and ship that feature as it currently is.
As the default setting will keep the previous state it's an optional thing to use.
