### ISSUE TITLE
Add creation date to Tag

### ISSUE THREAD

**Issue by edmundkwok** [klausmeyer/docker-registry-browser#4]
First off, this Registry Browser is perfect to list all images easily and deleting them as well. Makes things so much easier than using the command line ;) Thanks for all the work done!

One thing that would be really helpful is to add the Tag creation date in the list page and detail page. That way we can identify old tags and delete them accordingly.

**Comment by klausmeyer** [comment]
Hi and thanks for your feature request. It's great to hear people are actually using this project.

Unfortunately I can't show the "created_at" of tags at the moment since this application is a stateless client for the registry's API which currently does not provide this information:

https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md

I'll keep this issue around - maybe a future version of the API will include this information.

You might want to have a look at the [SUSE/Portus](https://github.com/SUSE/Portus) project which is a much more advanced "registry interface" which also utilises a database that will be updated on every push to the connected registry (via webhook) and might therefore include the "created_at" attribute.

**Comment by klausmeyer** [comment]
Looks like I've found a way to show that information on the tag details page.

Release `v1.3.0` tag and updated `latest` tag will be available on Docker-Hub soon.
